import { Column, Hr, Row, Section, Text } from '@react-email/components';
import { BaseTemplate } from '../components/base-template';
import CardHeader from '../components/card-header';
import { sharedPreviewProps, sharedTemplateProps } from '../props';

interface PruneReportEmailProps {
  logoURL: string;
  appURL: string;
  totalSpaceReclaimed: string;
  containerSpaceReclaimed: string;
  imageSpaceReclaimed: string;
  volumeSpaceReclaimed: string;
  buildCacheSpaceReclaimed: string;
  time: string;
}

export const PruneReportEmail = ({
  logoURL,
  appURL,
  totalSpaceReclaimed,
  containerSpaceReclaimed,
  imageSpaceReclaimed,
  volumeSpaceReclaimed,
  buildCacheSpaceReclaimed,
  time,
}: PruneReportEmailProps) => {
  return (
    <BaseTemplate logoURL={logoURL} appURL={appURL}>
      <CardHeader title="System Prune Report" />

      <Section style={totalSectionStyle}>
        <Text style={totalLabelStyle}>Total Reclaimed</Text>
        <Text style={totalValueStyle}>{totalSpaceReclaimed}</Text>
      </Section>

      <Section style={breakdownSectionStyle}>
        <Row style={infoRowStyle}>
          <Column style={labelColumnStyle}>
            <Text style={labelStyle}>Containers:</Text>
          </Column>
          <Column>
            <Text style={valueStyle}>{containerSpaceReclaimed}</Text>
          </Column>
        </Row>

        <Hr style={dividerStyle} />

        <Row style={infoRowStyle}>
          <Column style={labelColumnStyle}>
            <Text style={labelStyle}>Images:</Text>
          </Column>
          <Column>
            <Text style={valueStyle}>{imageSpaceReclaimed}</Text>
          </Column>
        </Row>

        <Hr style={dividerStyle} />

        <Row style={infoRowStyle}>
          <Column style={labelColumnStyle}>
            <Text style={labelStyle}>Volumes:</Text>
          </Column>
          <Column>
            <Text style={valueStyle}>{volumeSpaceReclaimed}</Text>
          </Column>
        </Row>

        <Hr style={dividerStyle} />

        <Row style={infoRowStyle}>
          <Column style={labelColumnStyle}>
            <Text style={labelStyle}>Build Cache:</Text>
          </Column>
          <Column>
            <Text style={valueStyle}>{buildCacheSpaceReclaimed}</Text>
          </Column>
        </Row>
      </Section>

      <Section style={{ marginTop: '20px' }}>
        <Text style={footerStyle}>Generated by Arcane at {time}</Text>
      </Section>
    </BaseTemplate>
  );
};

export default PruneReportEmail;

const totalSectionStyle = {
  marginTop: '20px',
  textAlign: 'center' as const,
  backgroundColor: 'rgba(15, 23, 42, 0.5)',
  border: '1px solid rgba(148, 163, 184, 0.1)',
  padding: '20px',
  borderRadius: '12px',
};

const totalLabelStyle = {
  fontSize: '12px',
  lineHeight: '18px',
  letterSpacing: '0.08em',
  textTransform: 'uppercase' as const,
  color: '#94a3b8',
  margin: '0',
};

const totalValueStyle = {
  fontSize: '30px',
  lineHeight: '36px',
  fontWeight: '700' as const,
  color: '#34d399',
  margin: '8px 0 0 0',
};

const breakdownSectionStyle = {
  marginTop: '18px',
  backgroundColor: 'rgba(15, 23, 42, 0.5)',
  border: '1px solid rgba(148, 163, 184, 0.1)',
  padding: '20px',
  borderRadius: '12px',
};

const infoRowStyle = {
  marginBottom: '0',
};

const labelColumnStyle = {
  width: '180px',
  verticalAlign: 'top' as const,
  paddingRight: '12px',
};

const labelStyle = {
  fontSize: '14px',
  fontWeight: '600' as const,
  color: '#94a3b8',
  margin: '8px 0',
};

const valueStyle = {
  fontSize: '14px',
  color: '#e2e8f0',
  margin: '8px 0',
  wordBreak: 'break-word' as const,
  fontFamily: 'monospace',
};

const dividerStyle = {
  borderColor: 'rgba(148, 163, 184, 0.2)',
  margin: '4px 0',
};

const footerStyle = {
  fontSize: '12px',
  lineHeight: '18px',
  color: '#94a3b8',
  margin: '0',
};

PruneReportEmail.TemplateProps = {
  ...sharedTemplateProps,
  totalSpaceReclaimed: '{{.TotalSpaceReclaimed}}',
  containerSpaceReclaimed: '{{.ContainerSpaceReclaimed}}',
  imageSpaceReclaimed: '{{.ImageSpaceReclaimed}}',
  volumeSpaceReclaimed: '{{.VolumeSpaceReclaimed}}',
  buildCacheSpaceReclaimed: '{{.BuildCacheSpaceReclaimed}}',
  time: '{{.Time}}',
};

PruneReportEmail.PreviewProps = {
  ...sharedPreviewProps,
  totalSpaceReclaimed: '3.4 GB',
  containerSpaceReclaimed: '480 MB',
  imageSpaceReclaimed: '2.1 GB',
  volumeSpaceReclaimed: '612 MB',
  buildCacheSpaceReclaimed: '228 MB',
  time: 'Tue, 10 Feb 2026 19:30:00 UTC',
};
