useTabs: true
singleQuote: true
trailingComma: none
printWidth: 130
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
  - "@prettier/plugin-oxc"
overrides:
  - files: "*.svelte"
    options:
      parser: svelte
  - files:
      - "**/*.{ts,mts,cts,tsx}"
    options:
      plugins:
        - "@prettier/plugin-oxc"
      parser: oxc-ts
