packages:
  - frontend
  - tests
  - email-templates

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp

overrides:
  devalue: ^5.6.2
  valibot: ^1.2.0
  validator: ^13.15.22
  cookie: ^0.7.0
  next: ^16.1.5
  undici: ^6.23.0
  vite: ^8.0.0-beta.12
  '@sveltejs/vite-plugin-svelte': ^7.0.0-next.0
