FROM alpine:3

ARG TARGETARCH
ARG TARGETVARIANT
ARG VERSION="dev"
ARG REVISION="unknown"

WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata curl
RUN mkdir -p /app/data

COPY ./backend/.bin/arcane-linux-${TARGETARCH}${TARGETVARIANT} ./arcane

ENV ENVIRONMENT=production
ENV GIN_MODE=release
ENV PORT=3552

LABEL org.opencontainers.image.authors="OFKM Technologies" \
	org.opencontainers.image.url="https://github.com/getarcaneapp/arcane" \
	org.opencontainers.image.documentation="https://github.com/getarcaneapp/arcane/blob/main/README.md" \
	org.opencontainers.image.source="https://github.com/getarcaneapp/arcane" \
	org.opencontainers.image.version=${VERSION} \
	org.opencontainers.image.revision=${REVISION} \
	org.opencontainers.image.licenses="BSD-3-Clause" \
	org.opencontainers.image.ref.name="arcane" \
	org.opencontainers.image.title="Arcane" \
	org.opencontainers.image.description="Modern Docker Management, Made for Everyone" \
	com.getarcaneapp.arcane.updater="false" \
	com.getarcaneapp.arcane.server="true"

EXPOSE 3552
VOLUME ["/app/data"]

CMD ["./arcane"]